### PR TITLE
Geometry package optimizations + Rotation class

### PR DESCRIPTION
**Pull request by mtsamis**
This is a pull request with a lot of improvements for the dyn4j.geometry package. Changes include:

- A new class: Rotation. This class represents a rotation and provides efficient operations with it. Currently all methods including rotations that are exposed to the user take a scalar parameter of radians. That means that each time the sine and cosine must be calculated again which are very slow functions. Also a lot of shapes use sin/cos and the even slower atan2 function to handle local rotation.
The Rotation class is my suggestion for solving those issues: it stores precomputed sin and cos values (without exposing them to the user) and implements a lot of useful operations without resorting to slow trigonometric functions. The user can now use a Rotation object to apply rotations to shapes, vectors and transforms without the extra overhead. Also shapes use internally a rotation object to represent rotation efficiently. Internal passing of sin/cos has been replaced with a Rotation object leading to more clean code.
- An improvement for getFarthestPoint/Feature for the Polygon class that makes polygons simulations around 1.5-2 times faster (especially for polygons with high vertex count)
- Various optimizations in Slice class alongside the elimination of trigonometric function calls that give an overall 2x performance improvement
- Eliminated the performance penalty of rotated Ellipse and HalfEllipse and made some extra optimizations for the HalfEllipse class
- Removed RegularPolygon because (after the improvement in Polygon mentioned above) it was substantially slower in all cases and served no purpose
- Small improvements in other classes

Apart from the performance benefits I think the Rotation class improves the code quality and provides a clean interface for the user to handle rotations. @wnbittle you can check whether you like the naming of the new methods in the rotation class, since I wasn't sure for some.

This is not ready for merging yet as I haven't made all the necessary unit tests (I will add them here soon), but I made the PR so you can have a look at the changes and possibly discuss the new additions.

### CODE REVIEW

**Comment by mtsamis** [comment]
@wnbittle Hey William I have added most of the important unit tests as well. But this PR has now a lot of changes and there are still some small additions to be made from my part. Can I somehow make it easier for you to review this? Maybe I should split it into smaller PRs?
If there's some way to help you out with this just let me know

**Comment by wnbittle** [comment]
This looks good and I'm sorry for taking so long to review these and want you to know that I do appreciate the effort.  Can you address some comments of mine:

**Rotation class**
Do you think the common angle helpers would be used that often?  At first (and second) review I felt like it was just noise.  Can you give an example or two of how you think they would be used by an end user of the library?

**Vector2.rotateInv**
I'd prefer the Inv part spelled out to Inverse so that it's very clear as to it's purpose.  I'd also like it to match the Transform class inverse method naming "getInverseRotated" or "inverseRotate".  Does that make sense to you as a user of the library?

**getRotationObject**
I'm sure you feel the same, but I don't like the naming - so much that I'd rather break compatibility.  Unfortunately, I haven't come up with a better name either (I'm sure that's why it's named the way it is).  What I would like is that the existing getRotation method be renamed to getRotationAngle and the new method be called getRotation.  What are your thoughts on breaking compatibility for this?  My guess is that most users would be using the existing method for rendering at least.

**Comment by mtsamis** [comment]
Thanks. There's no problem with how much time it takes you to review those, you should take your time.

So, to answer your comments:

- About the Rotation class, there's indeed some noise around the common angle methods. We can probably remove those that are not very useful. I think we can:
1) remove all *static* methods that have to do with 45 degree angles (so we can have just 0/90/180/270 which I think are useful to have).
2) remove all methods that rotate by 45 + 90/180/270 since those are very unlikely to be useful, but keep rotate by 45 because it can be handy and combined to achieve some other rotations (maybe?).
- About Vector2.rotateInv, lol I don't even know why I didn't name them inverseRotate to begin with (I had in mind to make it similar with other classes; probably forgot to rename).
I will change the name to inverseRotate and fill in the getInverseRotated as well.
- getRotationObject. Exactly as you said; I was thinking about whether it would be worth it to break backwards compatibility and wasn't sure, hence the name.
Now that you bring this up I start to think it would be nice to have a getRotation/getRotationAngle pair, as you proposed (and break backwards compatibility, yes). Not only those are better describing names for the methods but that minor change will make dyn4j's users notice the new Rotation class which may be a plus. The final decision for this one is up to you though.

I'll also commit some missing unit tests (mostly for the Transform class) and do some extra polishing.

**Comment by mtsamis** [comment]
I've rename rotateInv to inverseRotate in the last commit (b4640f0).
Also I didn't create getInverseRotated methods since the Vector2 class has no getRotated family of methods either. I don't think they're useful enough to justify 12 new methods (for all the combinations), right?

**Comment by mtsamis** [comment]
Hey @wnbittle any progress with this? Just a small reminder

**Pull request merged**
