### PR TITLE
Arithmetic optimizations

### PR DESCRIPTION
**Pull request by mtsamis**
This pull request contains some meaningful optimizations in various calculations that result in more effecient code. Most of the changes are unrelated. Here's an outline of the changes:

- **Transform**
The transform class is the one with the most changes, almost the whole thing is changed.
The old Transform class used a 2x2 matrix to represent rotation and 2 extra variables for translation. But because the only possible transforms are rotation and translation (no shear, scale etc) the 2x2 matrix is superfluous. It always contains [cos(theta)    -sin(theta)] and [sin(theta)    cos(theta)].
The new Transform class has just 2 members for rotation (cost and sint) which saves space and greatly simplifies calculations. Also some mathematic optimizations have been made by using some properties and rearrangement.

- **Vector2**
Apart from some misc changes the most notable here is the new tripleProduct implementation.
Uses 4 multiplications instead of 8. This implementation is partially inlined in Gjk as well to slightly reduce the multiplications in the hot path of execution.

- **Gjk**
See above; less multiplications in main detection code by taking advantage of the tripleProduct implementation.
Also rearrangment of some calculations that result in less multiplications.

- **Island**
Not very important changes. In the step where the settings maximum values are enforced some improvements can be done so less things are re calculated.

- **Vector3**
Really minor changes 

If you have any questions I can explain in more detail

### CODE REVIEW

**Comment by wnbittle** [comment]
This looks really good.  Let me pull it down and do some testing.  All unit test pass right?

**Comment by mtsamis** [comment]
Hey William,
I checked the tests, there where three failing tests but they where not because of actual errors. I made a small change that makes one of those go away (TransformTest:319 expected 0.0 but got -0.0 which is the same anyway). The other two are:
 - CircleSliceTest.gjkDistance:330 expected:<0.449> but was:<0.45>
 - TransformTest.lerp:278 expected:<1.6323813093168174> but was:<1.6323813093168176>
The first one should be ok since it has an error delta 1.0e-3 (maybe the test fails because of small floating point inaccuracies) and the second is just a small change in precision coming from the new changes (possible solution is to add a small delta there as well?).
I don't know how you would prefer those to be resolved so I post this here for you to decide.

**Comment by wnbittle** [comment]
Yeah, it should compare using an appropriate delta.  I have to change these slightly sometimes too.

**Comment by wnbittle** [comment]
Just wanted to confirm - are you finished with your changes to the junit tests and ready to merge?

**Comment by mtsamis** [comment]
Sorry for the slight delay with this, I have just pushed the adjusted unit tests. All tests pass now.
I just added a small delta to TransformTest and changed the constant 0.449 to 0.450 (because the original computation resulted in 0.449999999... so 0.45 is a better testing value).
Everything is ready to merge now!

**Comment by mtsamis** [comment]
Hey William, is there anything else needed? This is ready to merge

**Comment by wnbittle** [comment]
Nope.  The only thing I need now is time :)

**Comment by mtsamis** [comment]
Alright, sure ;)

**Comment by wnbittle** [comment]
Finally got around to reviewing again.  This looks great - great finds in the Transform class for sure.

**Pull request merged**
