### PR TITLE
Mavenize the project

### PR DESCRIPTION
**Pull request by io7m**
Hello.

I recently needed to use Dyn4j in an [OSGi](https://www.osgi.org/) environment. Unfortunately, the Dyn4j jar didn't have any OSGi headers defined. Rather than add OSGI headers by hand (a very error-prone process), I took the opportunity to move the whole codebase to Maven conventions and add POM files for each module.

```
Mavenize the project

This reorganizes the source and resource files to match Maven/Gradle
conventions. Primarily, this means moving Java source files into
src/main/java, and moving resource files into src/main/resources.

It adds POM files for each subproject (the core, examples, sandbox,
and unit tests) that build jar files of bytecode, jar files of sources,
and jar files of JavaDoc. Additionally, it uses the Maven Bundle Plugin
to calculate accurate OSGi metadata, allowing Dyn4j to be used in OSGi
environments. The POM files conditionally use the GPG plugin to sign
all archives when the dyn4j.deployment property is defined. Finally,
the POM files use the Maven Nexus staging plugin to allow for deploying
jar files to Maven Central from the command line.
```

The test suite passes, and the sandbox application appears to work correctly. I'm not entirely sure about JNLP though, as I've not actually used it before. I'm not sure if I've broken it or not.

### CODE REVIEW

**Comment by io7m** [comment]
I'd be happy to walk you through all the changes, and discuss exactly what advantages this brings to the project.

**Comment by wnbittle** [comment]
Let me review the changes - I've been wanting to do this as well.

**Comment by wnbittle** [comment]
I manage this project out of Eclipse.  It looks like the project is broken.  Ideally, I would be able to pull down the project, open it in Eclipse, right click on the project and build with maven and it do everything you've stated.  Am I missing something?

**Comment by io7m** [comment]
Hm, that's strange. I switched to Intellij IDEA about a year ago, but Eclipse never had any problems with Maven projects when I was using it. I'll reinstall it today and see if there's something obviously wrong.

**Comment by io7m** [comment]
It appears that the problem was with the existing eclipse `.project` and `.settings` files in the source tree. I deleted these, removed the projects from the workspace, and then used `File -> Import... -> Existing Maven projects`. The projects imported without errors.

This is on Eclipse Neon 4.6.3, for reference.

**Comment by wnbittle** [comment]
Ok, cool.  I will take another look this evening.

**Comment by wnbittle** [comment]
Ok, I have it setup in Eclipse now.  This is looking good.  Being a novice at Maven, can you help fill in some gaps in my understanding:

1. Why are the tests, examples, and sandbox modules?  I don't intend to release these through maven.
2. What's the reasoning for splitting the resources and the source into two different source folders src/main/java & scr/main/resources?
3. Why does the main pom.xml define JUnit and JOGL dependencies?  I want to make sure that those using the released binary are not required to have these.
4. A follow up question is about core being a module.  When I deploy to maven for general availability I only want to deploy the core module, nothing else.  Will this work with the current setup?
5. What's the process with PGP and sonatype? Does the build prompt for credentials and the signing key?  I want to make sure I don't inadvertently check them in.

Thanks,
William

**Comment by io7m** [comment]
> Why are the tests, examples, and sandbox modules? I don't intend to release these through maven.

Mainly this was to avoid having the core module depend on JOGL/GlueGen and/or anything else you might add at a later date. This gives you some freedom in that you can add as many new dependencies as you like for the purposes of tests or example code without those dependencies polluting the core library that others use. See below.

> What's the reasoning for splitting the resources and the source into two different source folders src/main/java & scr/main/resources?

This is a Maven convention. I think they kept the sources and resources separate in order to make it easier to process resources at compile time without accidentally mangling sources. See [the docs for the maven-resources-plugin](https://maven.apache.org/components/plugins/maven-resources-plugin/) for a rough guide to the sorts of things people do with resources at compile time. Some people go one step further and separate resources into `resources` and `resources-filtered` directories, subjecting the latter directory to various kinds of preprocessing. I don't have strong feelings on the sources/resources split convention either way, but I think it's a good idea to follow it as following conventions is what keeps all Maven projects familiar and uniform. Someone unfamiliar with the `dyn4j` codebase knows exactly where to find resources because they're in the same place as any other Maven project.

> Why does the main pom.xml define JUnit and JOGL dependencies? I want to make sure that those using the released binary are not required to have these.

It actually just defines the versions so that you only have to specify them once. The `dependencyManagement` section basically pre-declares dependency versions, and then
the `dependencies` sections in each module can refer to those dependencies without having to repeat the version numbers. You can see that the core module doesn't have a `dependencies` section and therefore has no dependencies.

> A follow up question is about core being a module. When I deploy to maven for general availability I only want to deploy the core module, nothing else. Will this work with the current setup?

Yep, no problem there. You'd just specify the `dyn4j-parent` and `dyn4j`  modules using the `--projects` command line flag:

```
$ mvn --projects .,core deploy
```

The `--projects` option specifies a comma-separated list of the modules you want to include in the build. In this case, `.` refers to the `dyn4j-parent` module and `core` is self explanatory. You do need to deploy `dyn4j-parent` to Central as this declares the various plugin and dependency versions used by `core`: When someone declares a dependency on `org.dyn4j:dyn4j`, their Maven will pull the `org.dyn4j:dyn4j-parent` POM from Central in order to get at the various bits of metadata contained within.

> What's the process with GPG and sonatype? Does the build prompt for credentials and the signing key? I want to make sure I don't inadvertently check them in.

The way it works right now is that the `maven-gpg-plugin` is bound to the [verify](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) phase by default. It's configured to run in a [profile](https://maven.apache.org/guides/introduction/introduction-to-profiles.html) that's only activated if a property `dyn4j.deployment` is defined. You could, for example, enable the profile if you were to do:

```
$ mvn -Ddyn4j.deployment=true verify
```

The reason for putting it in a profile is that, if the declaration wasn't in a profile, anyone building the library from source would be asked to PGP sign it. I'd guess most developers who aren't routinely deploying packages to Central don't have PGP set up properly, so this would be very annoying.

Rather than specify a property on the command line, the way I do it in my own projects is to put the following in my `~/.m2/settings.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<settings
  xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <profiles>
    <profile>
      <id>io7m</id>
      <properties>
        <gpg.useagent>true</gpg.useagent>
        <gpg.keyname>io7m.com (2017 release-signing)</gpg.keyname>
        <io7m.deployment>true</io7m.deployment>
      </properties>
    </profile>
  </profiles>

  <activeProfiles>
    <activeProfile>io7m</activeProfile>
  </activeProfiles>

</settings>
```

The above is pretty self explanatory. It sets `io7m.deployment` to `true` and declares some properties that the `maven-gpg-plugin` reads in order to determine what key to use for signing and whether or not to talk to a running `gpg-agent` instance. In my environment, when I use `mvn deploy` my GPG agent pops up a dialog box asking me for my GPG passphrase. Obviously in your case you'd define `dyn4j.deployment` instead!

As for actually deploying to Central, you need the following in `~/.m2/settings.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<settings
  xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

...
  <servers>
    <server>
      <id>sonatype-nexus-staging</id>
      <username>your sonatype user name here</username>
      <password>your sonatype password here</password>
    </server>
  </servers>

</settings>
```

You'd insert the username/password that you normally use for the Sonatype web interface there. When you type `mvn deploy`, the `nexus-staging-plugin` sees that you're deploying to the default server (`sonatype-nexus-staging` in this case, as declared in the main `pom.xml`) and looks up the corresponding credentials defined in your `settings.xml`. The packages will be pushed to a staging repository on Central, and then you can use the command line to _close_ and _release_ the staging repository the same way that you would via the web interface. To see the list of current staging repositories after the initial `mvn --projects .,core deploy`:

```
$ mvn nexus-staging:rc-list
```

On your first deploy, there'll be a repository in the list that will be named something like `org-dyn4j-1000`. You'd then do:

```
$ mvn nexus-staging:rc-close -DstagingRepositoryId=org-dyn4j-1000
```

Assuming that your artifacts pass the various quality checks they perform (you'll get an error if they don't), you can then do:

```
$ mvn nexus-staging:rc-release -DstagingRepositoryId=org-dyn4j-1000
```

I'm fairly certain that all of the required elements are there in the POM, so there shouldn't be any failures.

**Comment by wnbittle** [comment]
Great this helps a lot.  I think I'm getting what you are saying now.

So basically, to make dyn4j truely maven-ized, but yet have the core library declare no dependencies you had to split the other sources (tests, sandbox, and examples) into their own modules (and core as well).  This then allows the dyn4j project to add dependencies, but the core will remain dependency-less.

One thing I'm not clear on is what exactly is deployed to maven central.  Is it just the core module?  If it's all the modules, my next question would be is this a common practice?  If that is the case, then I wonder if a better design might be to split the tests, sandbox, and examples into their own maven projects & repos, and have them depend on this one.  

What are you thoughts about splitting the projects into different maven projects (which wouldn't be deployed)?

William

**Comment by io7m** [comment]
> So basically, to make dyn4j truely maven-ized, but yet have the core library declare no dependencies you had to split the other sources (tests, sandbox, and examples) into their own modules (and core as well). This then allows the dyn4j project to add dependencies, but the core will remain dependency-less.

Yep, that's right.

> One thing I'm not clear on is what exactly is deployed to maven central. Is it just the core module? If it's all the modules, my next question would be is this a common practice? If that is the case, then I wonder if a better design might be to split the tests, sandbox, and examples into their own maven projects & repos, and have them depend on this one.

I think it is common practice to deploy everything, yes. But like I said, you control exactly what gets deployed by specifying an explicit set of modules with `--projects` when you type `mvn deploy`. If you don't specify the modules explicitly, everything is deployed. Personally, I'd deploy the whole lot. I switched to using Maven Central a couple of years back as the canonical hosting for all of my libraries (including all of their tests and example code) and associated applications, and haven't looked back. 

Another thing I see people do fairly frequently (and I've taken to doing this as well) is to deploy additional runnable "one-jar" files for any applications that a library includes. My most recent example of this is [smf](https://io7m.github.io/smf/): You can see on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.io7m.smfj%22) that the `com.io7m.smfj.cmdline` module includes an extra `main.jar` (produced with [Maven Shade](https://maven.apache.org/components/plugins/maven-shade-plugin/)). This `main.jar` contains all of the dependencies embedded in the jar file so that users can run it with `java -jar main.jar` without needing to set up a classpath or download any dependencies manually. This might be something to consider for the sandbox. I'd be happy to contribute extra definitions that sets this up (assuming that we can get JOGL to cooperate!).

> What are you thoughts about splitting the projects into different maven projects (which wouldn't be deployed)?

I don't see a great deal of benefit to doing this. I could maybe see the sandbox being split into its own separate project given that it's more of an "application", but I'd consider the tests and example code to be pretty heavily coupled to the core and therefore there's a benefit to keeping them all as modules of the same project: They all get built and tested together.

I think if you were to separate all of the modules into their own projects, you'd still want to keep the `dyn4j-parent` parent POM in order to avoid duplicating version numbers and plugin definitions across all of the new projects.

**Comment by io7m** [comment]
> I switched to using Maven Central a couple of years back as the canonical hosting for all of my libraries (including all of their tests and example code) and associated applications, and haven't looked back.

I probably should have mentioned that there's a little-known feature of Maven Central in that deployed artifacts are accessible as simple static file downloads and can therefore be linked to directly from "download" pages on sites and so on:

https://repo1.maven.org/maven2/org/dyn4j/dyn4j/3.1.11/

**Comment by io7m** [comment]
I'll close this PR so that I can reset my own fork to your master branch.

**Pull request closed without merging**
