### PR TITLE
New broadphase detector

### PR DESCRIPTION
**Pull request by mtsamis**
So after a lot of experimentation, I made a new broadphase detector that on most cases performs 2x-3x times faster than the current broadphase DynamicAABBTree! Also as a bonus, the new broadphase detector is based on ideas from DynamicAABBTree in a way that it will not perform worse than it in any case (by a significant amount), so it's a net win.

Although DynamicAABBTree is a good broadphase it has some important flaws:
- performance was very dependent on body insertion/update order. The same bodies with different order could make the broadphase take twice as much time.
- The tree structure is getting worse and worse while the simulation advances. This is a 'typical' problem with R-tree-like 
- For few bodies (up to couple hundreds) it would perform worse than a O(n^2) brute-force collision detection routine

My new implementation addresses those shortcomings and also contains a wide variety of new optimizations and algorithmic improvements that all together give this speed increase I mentioned.
The implementation is explained in a good depth inside the new classes, but if there are any questions feel free to ask.

I understand this needs a bit of time to work out, but the results where good so I wanted to share this.
I also suggest this is used as the default broadphase in the future releases, but that's up to you William.

I'm also attaching 2 sample scenarios with the old and new Broadphase that showcase the changes.
The numbers in seconds below is the time spent in total in the broadphase algorithm for updating and detecting the collisions. Apart from the general speedup, note how while body count is same, due to other order dynamicAABBTree takes 4 seconds more in one case!

small to large order
dynamicAABBTree:    13.5 seconds
lazyAABBTree:           6.1 seconds
		
large to small order
dynamicAABBTree:    17.5 seconds
lazyAABBTree:           5.7 seconds

(note: jars are built with java 11)
[examples.zip](https://github.com/dyn4j/dyn4j/files/3010418/examples.zip)

### CODE REVIEW

**Comment by wnbittle** [comment]
This looks very promising.  I haven't had a chance to do testing yet, but can you go ahead and add some junit tests for the new broadphase?

> * performance was very dependent on body insertion/update order. The same bodies with different order could make the broadphase take twice as much time.
> * The tree structure is getting worse and worse while the simulation advances. This is a 'typical' problem with R-tree-like
> * For few bodies (up to couple hundreds) it would perform worse than a O(n^2) brute-force collision detection routine

Can you elaborate more on your findings?  Some specific questions I have are:

- For the insertion order issue - was this improved if larger bodies were inserted first, or more generally, was there a consistent metric that increased (or decreased) performance?
- What happened to the tree structure?  If it's the problem of the tree structure reducing down to a linked list, that should already be handled by the auto-balancing.  What was the structure that you observed in some of your simulations?
- Are you saying that the implementation has worse _complexity_ or _runtime performance_ when compared to a brute force algorithm?

**Comment by mtsamis** [comment]
Sure, I will write some unit tests as soon as I find the time. About your questions:

- For the insertion order, the metric is that smaller bodies should be inserted first. This makes sense, because inserting the big bodies first will make all inner AABB nodes as big. In the new broadphase I keep the fixtures sorted by fixture radius. I have tested other metrics as well but this seems to be the most important. Reverse order causes a performance drop of up to 30-40%.

- The problem is not that the tree is reduced down to a list; Actually this can't happen (as you said) as the tree is balanced. The problem is that height balancing the tree doesn't guaranty good performance, because when detecting it can happen that we descend both left and right sub-trees. What's important is the AABB overlap between internal nodes, because that determines how fast the tree traversal will be.
While making broadphases I was rendering the internal AABBs to see and understand more about the structure of the trees. There I saw that the default dynamicAABBTree gets quite bad after a lot of iterations. It's not easy to describe, but it was as the previous body positions where (kind of) leaving a trail behind and gradually the tree was becoming very dense with a lot of overlap.

- DynamicAABBTree has *worse runtime performance for small body count* (for me up to 100s of bodies, brute force broadphase is somewhat faster). Of course as body count increases, brute force gets quite worse than it, but it is not desirable to have a broadphase that is slower than bruteforce up to 100s of bodies.

The new broadphase fixes those two issues (fixture order & performance degradation) and also contains all the other optimizations. Also, it is worthwhile to note that because it does not expand AABBs fewer bodies make it into the narrowphase which wields even more performance benefits.
If you have any more questions, hit me up.

**Comment by mtsamis** [comment]
I see that there are no tests for the existing broadphase detectors, is there a reason for that?
I was thinking that I could make an implementation of the simple brute force broadphase detector and test the new broadphase by comparing it’s results to the brute force one (maybe on a deterministic randomizes sequence of operations). How does this sound?

**Comment by wnbittle** [comment]
There’s one called BroadphaseTest which tests the basics of its functionality: add, remove, update, batchUpdate or whatever.

A brute force algorithm would be a good addition.  No comparisons necessary, but that type of information would be good to highlight in the javadoc.

Regarding expanded AABBs: the original intent was to expand them slightly so updates to the broadphase occur less frequently with the assumption that in most simulations the majority of bodies are not moving.  I think it’s a nice feature to have and would recommend its inclusion.  If a user of the class doesn’t want that they can make the expansion size 0.

Really appreciate the discussion and contributions btw

**Comment by mtsamis** [comment]
Thanks! It's been quite fun working on dyn4j and I still have lots of things to do.

I just noticed the BroadphaseTest, I'll make some entries for the new broadphase. I'll fill in a brute-force broadphase as well in the future; it's indeed a nice thing to have, I'll probably make some test cases with it for other broadphases since I like this idea. It will make a good test for any other broadphase algorithm.

Now about the AABB expansion: The reason that it is not included anywhere is because there are no 'real' updates to bodies. If you check up the code and comments I wrote, the tree is built from scratch every time to detect bodies. So expanding bodies won't have any benefits (like it does in DynamicAABBTree) and will only make the results less accurate (include more false-positives).
Maybe I should mention in the javadoc that although the setExpansion methods exist (from abstract broadphase class) they don't affect any of the behavior.

If it's still not clear why expansion won't do any good for this particular broadphase I can explain in more detail.

**Comment by wnbittle** [comment]
Ahh ok, I missed that detail.  If the tree is rebuilt then you are correct the expansion isn’t useful.

**Comment by mtsamis** [comment]
Hey William, I made some new changes/improvements and bug fixes as requested.
I added a new method  in broadphase that informs whether a broadphase implementation supports AABB expansion. I wanted to separate the expansion code in another interface but this could break some applications (so I avoided it). Please see the related docs and changes and tell me if you like this solution.
Then I refactored the BroadphaseTest class to test the new LazyAABBTree and also made testing more automated there (The test takes an instance and runs all tests, instead of copy-pasting methods for each instance).
I also made LazyAABBTree a bit more strict in some aspects, regarding when are the AABBs computed. Originally AABB creation was as lazy as possible, but now they get created when added/updated to ensure more predictable behavior.

**Comment by mtsamis** [comment]
I will also be adding a brute force Broadphase and related tests but after this pull request is closed.

**Pull request merged**
